services:
  server:
    image: mysql:8.0
    container_name: db_servidor
    restart: always
    environment:
      MYSQL_DATABASE: banco_clientes
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306